export enum EStore {
    ADD_USER = 'ADD_USER',
    DELETE_USER = 'DELETE_USER',
    LOAD_USERS = 'LOAD_USERS',
    OPEN_CREATE_USER_DIALOG = 'OPEN_CREATE_USER_DIALOG',
    CLOSE_CREATE_USER_DIALOG = 'CLOSE_CREATE_USER_DIALOG',
}